### ISSUE TITLE
Add support for RTD previews of MEPs

### ISSUE THREAD

**Issue by agoose77** [executablebooks/myst-enhancement-proposals#16]
### Context

Given that GH doesn't support MyST, reviewing MEPs in GitHub's UI is suboptimal.

### Proposal

It would be nice if we used the RTD PR building to render MEPs. This would make reviewing MEPs slightly more convenient when on mobile, or lazy!

**Comment by chrisjsewell** [comment]
Heya @agoose77 this already happens no?

**Comment by agoose77** [comment]
:facepalm:
